version: "3"

services:
  backend:
      container_name: datamod_backend
      env_file:
        - ./config/env/creds.env
      build:
        context: ./app/backend
        dockerfile: /app/backend/Dockerfile
    command: ["flask", "run"]
    ports:
      - "5000:5000"
  frontend:
    container_name: datamod_frontend
    build:
      context: ./app/frontend
      dockerfile: /app/frontend/Dockerfile"
    command: ["yarn", "start"]
    ports:
      - "3000:3000"
    depends_on:
      - backend