version: "3"
services:
  backend:
    container_name: datamod_backend
    env_file:
      - ./config/env/creds.env
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=server.py
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    ports:
      - "5000:5000"
    volumes:
      - ./app/backend/pyData:/src/api
  frontend:
    container_name: datamod_frontend
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    command: ["yarn", "start"]
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./app/frontend/datamod:/src/datamod
